### ISSUE TITLE
dev branch is broken

### ISSUE THREAD

**Issue by myedibleenso** [myedibleenso/ling-sleuth#3]
`./run.py` gives me the following error:

```
Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from app import app, db
  File "/Users/gus/github/ling-sleuth/app/__init__.py", line 28, in <module>
    from app import views, models # avoid circular references
  File "/Users/gus/github/ling-sleuth/app/views.py", line 5, in <module>
    from .quizzes import *
  File "/Users/gus/github/ling-sleuth/app/quizzes.py", line 83, in <module>
    class PartOfSpeech(Form):
  File "/Users/gus/github/ling-sleuth/app/quizzes.py", line 86, in PartOfSpeech
    score = Score(quiz)
  File "/Users/gus/github/ling-sleuth/app/quizzes.py", line 20, in __init__
    self.questions = self.quiz.questions #QuestionLibrary.query.filter_by(quiz=self.quiz.quiz_id).all() #self.quiz.questions
AttributeError: 'NoneType' object has no attribute 'questions'
```

@sjcjohnston are there some changes your forgot to push?

**Comment by sjcjohnston** [comment]
hmm... looks like a db error.  It is possible that the db and migration
files aren't syncing up properly with the dropbox.  I've replaced the old
ones in Dropbox with the ones I had been using within the lingsleuth
directory.  Let me know if that fixes the problem.

As far as the CSVs, they're up there - within the app directory, along with
the python scripts.  Probably not the best/cleanest place for them, and I
can change that later.  Regardless, whether the CSVs are committed should
have no affect on the normal running of the code - they're just used as a
"storehouse" for the data that is in the database, and a method to easily
update/add information to the db.  Otherwise they're not called on a
regular basis.

Samuel Johnston
University of Arizona
sjcjohnston@email.arizona.edu

**Comment by myedibleenso** [comment]
Looks like you hadn't pushed some changes?  I pulled this morning and there were a number of changes across files.  It runs now, but logging in throws this error:

```
  File "/Users/gus/github/ling-sleuth/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gus/github/ling-sleuth/app/views.py", line 50, in login_with_provider
    handle_user(result)
  File "/Users/gus/github/ling-sleuth/app/views.py", line 234, in handle_user
    registered_user = register_user(result)
  File "/Users/gus/github/ling-sleuth/app/views.py", line 238, in register_user
    user = User(username=result.user.name, provider=result.provider.name, email=result.user.email, xp=0.001, registration=True)
  File "<string>", line 4, in __init__

  File "/Users/gus/github/ling-sleuth/venv/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 269, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/Users/gus/github/ling-sleuth/app/models.py", line 33, in __init__
    if User.query.filter_by(username=self.username).first().xp is None:
AttributeError: 'NoneType' object has no attribute 'xp'
```
