### ISSUE TITLE
dev is broken

### ISSUE THREAD

**Issue by myedibleenso** [myedibleenso/ling-sleuth#5]
@sjcjohnston: running `python manage.py db init` fails with this error:

```
sqlalchemy.exc.OperationalError: (OperationalError) no such table: quizzes u'SELECT quizzes.id AS quizzes_id, quizzes.quiz AS quizzes_quiz, quizzes.description AS quizzes_description, quizzes.passing_threshold AS quizzes_passing_threshold, quizzes.passed AS quizzes_passed, quizzes.module_id AS quizzes_module_id \nFROM quizzes \nWHERE quizzes.quiz = ?\n LIMIT ? OFFSET ?' ('frequency', 1, 0)
```

**Comment by sjcjohnston** [comment]
@myedibleenso cannot recreate error.  Committed and pushed current working version in case there was a problem with the earlier version.  Odd because it shouldn't be working with an existing database where there would be a table missing.  The database and migrations directory have been deleted prior to running db init?

**Comment by myedibleenso** [comment]
@sjcjohnston try deleting/moving your `app.db` and `migrations` folder and see if you can initialize.

**Comment by myedibleenso** [comment]
I suspect there is a file you never added/tracked with git.  Try cloning the project in some other directory and see if you can get it running there.

**Comment by sjcjohnston** [comment]
@myedibleenso  Ok - bizzare, but go to quizzes.py.  Comment out lines 18-27.   Not a permanent fix by any means, but long story short, manage.py is importing code that tries to access the db prior to instantiation.  
Now (after commenting out):
python manage.py db init
python manage.py db migrate
python manage.py db upgrade
python manage.py reboot

Now uncomment the lines.  It should now work.  If not, re-comment the lines, re enter the db migrate and db upgrade commands once more.  Then uncomment.  Now it should work.

Let me know if this fixes it, and I can look for a more permanent solution.

**Comment by myedibleenso** [comment]
This worries me.

After using Google to log in for the first time I get this error:

```
AttributeError
AttributeError: 'NoneType' object has no attribute 'xp'

Traceback (most recent call last)
File "/Users/gus/github/ling-sleuth/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/gus/github/ling-sleuth/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/Users/gus/github/ling-sleuth/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/gus/github/ling-sleuth/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/Users/gus/github/ling-sleuth/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/gus/github/ling-sleuth/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/gus/github/ling-sleuth/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/gus/github/ling-sleuth/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/gus/github/ling-sleuth/app/views.py", line 50, in login_with_provider
handle_user(result)
File "/Users/gus/github/ling-sleuth/app/views.py", line 311, in handle_user
registered_user = register_user(result)
File "/Users/gus/github/ling-sleuth/app/views.py", line 315, in register_user
user = User(username=result.user.name, provider=result.provider.name, email=result.user.email, xp=0.001, registration=True)
File "<string>", line 4, in __init__
File "/Users/gus/github/ling-sleuth/venv/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 269, in _initialize_instance
return manager.original_init(*mixed[1:], **kwargs)
File "/Users/gus/github/ling-sleuth/app/models.py", line 33, in __init__
if User.query.filter_by(username=self.username).first().xp is None:
AttributeError: 'NoneType' object has no attribute 'xp'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
```
